## Pre-commit Workflow
# Last update: 2024-05-27

# Save this file to './.github/workflows/pre-commit-workflow.yaml'

# Name of the workflow
name: pre-commit

# Controls on when the workflow will run
on:
  pull_request:

  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  pre-commit:
    # Type of machine to run the job on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository content - https://github.com/actions/checkout
        uses: actions/checkout@v4

      # - name: Run PHP-CS-Fixer - https://github.com/marketplace/actions/cs-fixer-for-php
        # uses: erkenes/php-cs-fixer-action@main
        # with:
          # args: --config="./.github/workflows/.php-cs-fixer.dist.php"

      - name: Setup Python - https://github.com/actions/setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' #  Latest stable major version of Python

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Pre-commit action - https://github.com/pre-commit/action
        uses: pre-commit/action@v3.0.1
